name: Publish "shared" package to GitHub Packages
#on:
#  release:
#    types: [published]
on:
  push:
    paths:
      - "shared/src/**"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
            sparse-checkout: shared
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '24.9.0'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@kazurayam'
      - run: npm config delete always-auth
      - run: npm config delete key _auth _authToken username _password
      - run: cd shared && npm install --package-lock-only
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
